version: '3.6'

networks:
  default:
    name: ${NETWORK_NAME}
    external: true

services:
  mysql:
    container_name: ${__ENV__}_${MYSQL_CONTAINER_NAME}
    image: ${MYSQL_IMAGE}
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: ${TZ}
    ports:
      # ports include `inner` & `external`
      - ${MYSQL_PORT}:3306
    volumes:
      - ./etc/timezone:/etc/timezone:ro
      - ./etc/localtime:/etc/localtime:ro
      - ./etc/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./etc/mysql/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
      - ${DATA_DIR}/mysql/data:/var/lib/mysql:rw,cached
      - ${DATA_DIR}/mysql/logs:/var/log/mysql:rw,cached
      - ${DATA_DIR}/_backup/mysql:/var/backups:rw,cached
