version: '3.6'

networks:
  default:
    name: ${NETWORK_NAME}
    external: true

services:
  pma:
    container_name: ${__ENV__}_${PMA_CONTAINER_NAME}
    image: ${PMA_IMAGE}
    restart: always
    environment:
      TZ: ${TZ}
    ports:
      - ${PMA_PORT}:80
    volumes:
      - ./etc/timezone:/etc/timezone:ro
      - ./etc/localtime:/etc/localtime:ro
