version: '3.6'

networks:
  default:
    name: ${NETWORK_NAME}
    external: true

services:
  nginx:
    container_name: ${__ENV__}_${NGINX_CONTAINER_NAME}
    image: ${NGINX_IMAGE}
    restart: always
    labels:
      - sh.acme.autoload.domain=nginx
    environment:
      TZ: ${TZ}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/timezone:/etc/timezone:ro
      - ./etc/localtime:/etc/localtime:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:rw,cached
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:rw,cached
      - ./etc/nginx/ssl.d:/etc/nginx/ssl.d:rw,cached
      - ${SITE_DIR}:/usr/share/nginx/html:rw,cached
      - ${DATA_DIR}/nginx/logs:/var/log/nginx:rw,cached
